#!/usr/bin/env python3
"""
EMOS Contribution Tool

Manages additions and removals of Information Units based on metadata.json.
Ensures one change at a time for clean contributions.
"""

import os
import json
import sys
import re
from pathlib import Path


class ContributionTool:
    def __init__(self, project_root):
        self.project_root = Path(project_root)
        self.metadata_path = self.project_root / "metadata" / "metadata.json"
        self.metadata = None
        
    def load_metadata(self):
        """Load metadata.json"""
        with open(self.metadata_path, 'r') as f:
            self.metadata = json.load(f)
        
    def get_metadata_folders(self):
        """Extract all folder paths from metadata"""
        folders = {
            'databases': [],
            'generators': [],
            'predictors': []
        }
        
        for db in self.metadata['information_units']['databases']:
            folders['databases'].append({
                'path': db['folder_path'],
                'metadata': db
            })
            
        for gen in self.metadata['information_units']['generators']:
            folders['generators'].append({
                'path': gen['folder_path'],
                'metadata': gen
            })
            
        for pred in self.metadata['information_units']['predictors']:
            folders['predictors'].append({
                'path': pred['folder_path'],
                'metadata': pred
            })
            
        return folders
    
    def get_actual_folders(self):
        """Scan filesystem for actual Information Unit folders"""
        folders = {
            'databases': [],
            'generators': [],
            'predictors': []
        }
        
        base_paths = {
            'databases': self.project_root / "Information_Units" / "Databases",
            'generators': self.project_root / "Information_Units" / "Generators",
            'predictors': self.project_root / "Information_Units" / "Predictors"
        }
        
        for unit_type, base_path in base_paths.items():
            if base_path.exists():
                for item in base_path.iterdir():
                    if item.is_dir() and not item.name.startswith('_'):
                        rel_path = str(item.relative_to(self.project_root))
                        folders[unit_type].append(rel_path)
        
        return folders
    
    def compare_folders(self, metadata_folders, actual_folders):
        """Compare metadata vs actual folders and identify changes"""
        additions = []
        removals = []
        
        for unit_type in ['databases', 'generators', 'predictors']:
            meta_paths = set([f['path'] for f in metadata_folders[unit_type]])
            actual_paths = set(actual_folders[unit_type])
            
            # Find additions (in metadata but not in filesystem)
            for folder_info in metadata_folders[unit_type]:
                if folder_info['path'] not in actual_paths:
                    additions.append({
                        'type': unit_type,
                        'path': folder_info['path'],
                        'metadata': folder_info['metadata']
                    })
            
            # Find removals (in filesystem but not in metadata)
            for path in actual_paths:
                if path not in meta_paths:
                    folder_name = path.split('/')[-1]
                    removals.append({
                        'type': unit_type,
                        'path': path,
                        'name': folder_name
                    })
        
        return additions, removals
    
    def validate_changes(self, additions, removals):
        """Validate that changes meet contribution requirements"""
        total_changes = len(additions) + len(removals)
        
        if total_changes == 0:
            return 'no_change', None
        
        if total_changes > 1:
            return 'multiple_changes', {
                'additions': additions,
                'removals': removals
            }
        
        # Single change - return its type
        if len(additions) == 1:
            return 'addition', additions[0]
        else:
            return 'removal', removals[0]
    
    def create_readme(self, metadata):
        """Generate README.md content"""
        return f"""# {metadata['display_name']}

{metadata['description']}

## Overview

This module provides integration with {metadata['display_name']}.

## Key Methods

- `info()`: Returns description and capabilities
- `retrieve(params)` / `generate(params)` / `predict(params)`: Main functionality

## Usage

See the base class documentation for detailed usage instructions.
"""
    
    def create_init_file(self):
        """Generate __init__.py content"""
        return f"""# Auto-generated by EMOS contribution tool
"""
    
    def create_python_class(self, metadata, unit_type):
        """Generate Python class file content"""
        class_name = metadata['class_name']
        description = metadata['description']
        
        # Determine base class and method name
        base_classes = {
            'databases': ('BaseDatabase', 'retrieve'),
            'generators': ('BaseGenerator', 'generate'),
            'predictors': ('BasePredictor', 'predict')
        }
        
        base_class, method_name = base_classes[unit_type]
        
        folder_map = {
            'databases': 'Databases',
            'generators': 'Generators',
            'predictors': 'Predictors'
        }

        return f"""from Information_Units.{folder_map[unit_type]}.{base_class} import {base_class}


class {class_name}({base_class}):
    def __init__(self, {unit_type[:-1]}_name, logger=None):
        super().__init__({unit_type[:-1]}_name, logger)
    
    def info(self):
        msg = "{description}"
        return msg

    def {method_name}(self, inputs: dict) -> str:
        # Implement {method_name} logic here
        if self.logger:
            self.logger.log("{method_name.capitalize()}d from {metadata['display_name']}")
        return None
"""
    
    def create_information_unit_templates(self, change_info):
        """Create template files for new Information Unit"""
        metadata = change_info['metadata']
        unit_type = change_info['type']
        folder_path = self.project_root / change_info['path']
        
        # Create directory
        folder_path.mkdir(parents=True, exist_ok=True)
        print(f"  ✓ Created directory: {change_info['path']}")
        
        # Create README.md
        readme_path = folder_path / "README.md"
        with open(readme_path, 'w') as f:
            f.write(self.create_readme(metadata))
        print(f"  ✓ Created README.md")
        
        # Create __init__.py
        init_path = folder_path / "__init__.py"
        with open(init_path, 'w') as f:
            f.write(self.create_init_file())
        print(f"  ✓ Created __init__.py")
        
        # Create Python class file
        class_file_path = folder_path / metadata['file_name']
        with open(class_file_path, 'w') as f:
            f.write(self.create_python_class(metadata, unit_type))
        print(f"  ✓ Created {metadata['file_name']}")
        
        return metadata

    def build_information_unit_ui_labels(self, unit_type):
        """Render checkbox label rows for the given unit type using metadata.json"""
        indent = " " * 28
        labels = []
        for item in self.metadata['information_units'][unit_type]:
            value = item['id']
            label = item.get('display_name', item.get('name', value))
            singular = unit_type[:-1]
            labels.append(f"{indent}<label><input type=\"checkbox\" ui-type=\"{singular}\" value=\"{value}\"> {label}</label>")
        return "\n".join(labels)

    def update_information_unit_ui_lists(self):
        """Rewrite index.html checkbox lists from metadata so UI matches backend"""
        index_path = self.project_root / "index.html"
        if not index_path.exists():
            print("  ⚠ index.html not found; skipping UI update")
            return

        content = index_path.read_text()
        replacements = [
            ('databases', 'databasesList'),
            ('generators', 'generatorsList'),
            ('predictors', 'predictorsList'),
        ]

        for unit_type, dom_id in replacements:
            pattern = rf'(<div class="radio-group" id="{dom_id}">\n)(.*?)(\n\s*</div>)'
            new_labels = self.build_information_unit_ui_labels(unit_type)
            content, count = re.subn(pattern, rf"\1{new_labels}\3", content, flags=re.S)
            if count == 0:
                print(f"  ⚠ Could not update {dom_id} in index.html; please verify markup")

        index_path.write_text(content)
        print("  ✓ Updated UI checkboxes in index.html")
    
    def update_information_unit_factory_add(self, metadata, unit_type):
        """Add entry to Factory.py file"""
        folder_map = {
            'databases': ('Databases', 'DatabaseFactory.py'),
            'generators': ('Generators', 'GeneratorFactory.py'),
            'predictors': ('Predictors', 'PredictorFactory.py')
        }

        base_folder, factory_filename = folder_map[unit_type]
        factory_file = self.project_root / "Information_Units" / base_folder / factory_filename
        
        with open(factory_file, 'r') as f:
            content = f.read()
        
        # Prepare import and factory entry
        component_folder = metadata['name']
        class_name = metadata['class_name']
        unit_id = metadata['id']
        
        import_line = f"from Information_Units.{base_folder}.{component_folder}.{class_name} import {class_name}\n"
        factory_entry = f'    "{unit_id}": {class_name},\n'
        
        # Find where to insert import (after last import)
        lines = content.split('\n')
        last_import_idx = 0
        for i, line in enumerate(lines):
            if line.startswith('from Information_Units'):
                last_import_idx = i
        
        # Insert import
        lines.insert(last_import_idx + 1, import_line.rstrip())
        
        # Find factory dict and insert entry (before closing brace)
        factory_dict_name = f"{unit_type[:-1]}_factory"
        for i, line in enumerate(lines):
            if factory_dict_name in line and '{' in line:
                # Find closing brace
                for j in range(i, len(lines)):
                    if lines[j].strip() == '}':
                        lines.insert(j, factory_entry.rstrip())
                        break
                break
        
        # Write back
        with open(factory_file, 'w') as f:
            f.write('\n'.join(lines))
        
        print(f"  ✓ Updated {factory_file.name}")
    
    def update_information_unit_factory_remove(self, change_info):
        """Remove entry from Factory.py file"""
        unit_type = change_info['type']
        component_name = change_info['name']
        
        folder_map = {
            'databases': ('Databases', 'DatabaseFactory.py'),
            'generators': ('Generators', 'GeneratorFactory.py'),
            'predictors': ('Predictors', 'PredictorFactory.py')
        }

        base_folder, factory_filename = folder_map[unit_type]
        factory_file = self.project_root / "Information_Units" / base_folder / factory_filename
        
        with open(factory_file, 'r') as f:
            lines = f.readlines()
        
        # Remove import line and factory entry
        new_lines = []
        skip_next = False
        
        for line in lines:
            # Skip import line containing the folder name
            if f".{component_name}." in line and line.strip().startswith('from'):
                continue
            # Skip factory entry containing the folder name
            if f'{component_name}' in line and ':' in line and line.strip().startswith('"'):
                continue
            new_lines.append(line)
        
        # Write back
        with open(factory_file, 'w') as f:
            f.writelines(new_lines)
        
        print(f"  ✓ Updated {factory_file.name}")
    
    def remove_information_unit_folder(self, change_info):
        """Remove an Information Unit folder"""
        folder_path = self.project_root / change_info['path']
        
        if folder_path.exists():
            import shutil
            shutil.rmtree(folder_path)
            print(f"  ✓ Removed directory: {change_info['path']}")
        else:
            print(f"  ⚠ Directory not found: {change_info['path']}")
    
    def run(self):
        """Main execution flow"""
        print("\n" + "="*60)
        print("EMOS Contribution Tool")
        print("="*60 + "\n")
        
        # Load metadata
        print("Loading metadata.json...")
        self.load_metadata()
        
        # Get folders from metadata and filesystem
        metadata_folders = self.get_metadata_folders()
        actual_folders = self.get_actual_folders()
        
        # Compare
        additions, removals = self.compare_folders(metadata_folders, actual_folders)
        
        # Validate
        change_type, change_info = self.validate_changes(additions, removals)
        
        # Handle different scenarios
        if change_type == 'no_change':
            print("✓ No differences found!")
            print("  Metadata and filesystem are in sync.")
            print("\nSyncing UI checkboxes from metadata...")
            self.update_information_unit_ui_lists()
            print("\nPress Enter to exit...")
            input()
            return
        
        if change_type == 'multiple_changes':
            print("✗ ERROR: Multiple changes detected!\n")
            print("Only ONE addition or removal is allowed at a time.\n")
            
            if change_info['additions']:
                print("Additions found:")
                for add in change_info['additions']:
                    print(f"  + {add['path']}")
            
            if change_info['removals']:
                print("\nRemovals found:")
                for rem in change_info['removals']:
                    print(f"  - {rem['path']}")
            
            print("\n⚠ Please update metadata.json to include only one change.")
            sys.exit(1)
        
        # Check if it's a feature change
        if 'Features/' in change_info['path']:
            print("✗ WARNING: Feature updates not implemented yet!\n")
            print(f"Detected change in: {change_info['path']}")
            print("\nThis tool currently only supports Information Units:")
            print("  - Databases")
            print("  - Generators")
            print("  - Predictors")
            sys.exit(1)
        
        # Handle single valid change
        if change_type == 'addition':
            print("📦 ADDITION detected:\n")
            print(f"  Type: {change_info['type'].capitalize()[:-1]}")
            print(f"  Path: {change_info['path']}")
            print(f"  Name: {change_info['metadata']['display_name']}")
            print(f"  Description: {change_info['metadata']['description']}")
            
            print("\nThis will create:")
            print(f"  - {change_info['path']}/README.md")
            print(f"  - {change_info['path']}/__init__.py")
            print(f"  - {change_info['path']}/{change_info['metadata']['file_name']}")
            print(f"  - Update {change_info['type'].capitalize()[:-1]}Factory.py")
            
            confirm = input("\nProceed with addition? (yes/no): ").strip().lower()
            
            if confirm in ['yes', 'y']:
                print("\n🔨 Creating templates...\n")
                metadata = self.create_information_unit_templates(change_info)
                self.update_information_unit_factory_add(metadata, change_info['type'])
                self.update_information_unit_ui_lists()
                print("\n✓ Addition completed successfully!")
            else:
                print("\n✗ Addition cancelled.")
        
        elif change_type == 'removal':
            print("🗑️  REMOVAL detected:\n")
            print(f"  Type: {change_info['type'].capitalize()[:-1]}")
            print(f"  Path: {change_info['path']}")
            print(f"  Name: {change_info['name']}")
            
            print("\nThis will:")
            print(f"  - Delete {change_info['path']}/")
            print(f"  - Update {change_info['type'].capitalize()[:-1]}Factory.py")
            
            confirm = input("\n⚠ Proceed with removal? (yes/no): ").strip().lower()
            
            if confirm in ['yes', 'y']:
                print("\n🔨 Removing...\n")
                self.remove_information_unit_folder(change_info)
                self.update_information_unit_factory_remove(change_info)
                self.update_information_unit_ui_lists()
                print("\n✓ Removal completed successfully!")
            else:
                print("\n✗ Removal cancelled.")


if __name__ == "__main__":
    # Get project root (parent of metadata directory)
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    
    tool = ContributionTool(project_root)
    tool.run()
