"""Template generators for Information Units (Databases, Generators, Predictors)"""


def generate_readme(metadata):
    """Generate README.md content from template"""
    template = """# {display_name}

{description}

## Overview

This module provides integration with {display_name}.

## Key Methods

- `info()`: Returns description and capabilities
- `retrieve(params)` / `generate(params)` / `predict(params)`: Main functionality

## Usage

See the base class documentation for detailed usage instructions.
"""
    return template.format(**metadata)


def generate_init_file():
    """Generate __init__.py content"""
    return """# Auto-generated by EMOS contribution tool
"""


def generate_python_class(metadata, unit_type):
    """Generate Python class file content from template"""
    base_classes = {
        'databases': ('BaseDatabase', 'retrieve'),
        'generators': ('BaseGenerator', 'generate'),
        'predictors': ('BasePredictor', 'predict')
    }
    
    base_class, method_name = base_classes[unit_type]
    
    folder_map = {
        'databases': 'Databases',
        'generators': 'Generators',
        'predictors': 'Predictors'
    }
    
    template = """from Information_Units.{folder_type}.{base_class} import {base_class}


class {class_name}({base_class}):
    def __init__(self, {unit_singular}_name, logger=None):
        super().__init__({unit_singular}_name, logger)
    
    def info(self):
        msg = "{description}"
        return msg

    def {method_name}(self, inputs: dict) -> str:
        # Implement {method_name} logic here
        if self.logger:
            self.logger.log("{method_name_cap}d from {display_name}")
        return None
"""
    
    params = {
        'folder_type': folder_map[unit_type],
        'base_class': base_class,
        'class_name': metadata['class_name'],
        'unit_singular': unit_type[:-1],
        'description': metadata['description'],
        'method_name': method_name,
        'method_name_cap': method_name.capitalize(),
        'display_name': metadata['display_name']
    }
    
    return template.format(**params)
